---
# tasks file for ansible-role-consul-backup

- name: Set Consul snapshot filename
  set_fact:
    consul_backup_file: "{{ consul_backup_dir }}/consul.snapshot.{{ ansible_date_time.epoch }}.tgz"
  delegate_to: localhost
  become: no
  run_once: yes

- name: Backup Consul cluster to {{ consul_backup_dir }}/consul.snapshot.{{ ansible_date_time.epoch }}.tgz
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] | select('match', consul_base_ip) | list | first }}:{{ consul_port }}/v1/snapshot?dc={{ consul_datacenter }}"
    method: GET
    status_code: 200
    dest: "{{ consul_backup_file }}"
  delegate_to: localhost
  become: no
  run_once: yes

