---
# tasks file for ansible-role-haproxy-stop

- name: Stop Keepalived & HAProxy systemd services
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - "{{ keepalived_service }}"
    - "{{ haproxy_service }}"

