---
# tasks file for ansible-role-vault-remove

- name: Remove VAULT_ADDR profile
  file:
    path: /etc/profile.d/vault.sh
    state: absent

- name: Stop and disable vault service
  systemd:
    name: "{{ vault_service }}"
    state: stopped
    enabled: no
  register: command_result
  # Prevent Ansible failing when trying to stop a service that doesn't exist
  failed_when: "command_result is failed and ('find' not in command_result.msg and 'found' not in command_result.msg)"

- name: Delete vault systemd service config
  file:
    path: "/etc/systemd/system/{{ vault_service }}.service"
    state: absent

- name: Delete vault server directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ vault_certs }}"
    - "{{ vault_conf | dirname }}"
    - "{{ audit_path }}"

- name: Remove vault user
  user:
    name: "{{ vault_user }}"
    state: absent
    force: yes
    remove: yes
    
- name: Remove vault group
  group:
    name: "{{ vault_group }}"
    state: absent

- name: Remove vault binary
  file:
    path: "{{ vault_bin_path }}/vault"
    state: absent

# In case just the vault service is being removed and consul is still
# running, these steps are required to remove leftover data in kv store
# Re-deploying vault without clearing data will cause initialization problems
# First query consul itself to get a list of active consul servers
# This has two benefits:
# 1. Do not need to know/specify the consul servers within this role
# 2. Returns true list of active consul servers
# The only assumption here is that the service is called 'consul'
- name: Get list of active consul servers
  uri:
    url: "http://127.0.0.1:{{ consul_port }}/v1/catalog/service/consul"
    validate_certs: no
    method: GET
    status_code: 200
  become: no
  run_once: yes
  register: consul_service_out
  failed_when: consul_service_out.status != 200 and 'Errno 111' not in consul_service_out.msg

# This step is powerful enough to destroy vault data - it needs securing with ACLs!
# Loops through discovered consul servers
- name: Clear down consul backend data
  uri:
    url: "http://{{ item['Address'] }}:{{ consul_port }}/v1/kv/vault?recurse"
    validate_certs: no
    method: DELETE
    status_code: 200
  become: no
  run_once: yes
  register: clear
  loop: "{{ consul_service_out['json'] | default([]) }}"
  loop_control:
    label: "{{ item['Node'] }}"
  # Do not fail if consul has been removed already
  failed_when: clear.status != 200 and 'Errno 111' not in clear.msg 

