---
# tasks file for ansible-role-haproxy-start

- name: Start HAProxy & Keepalived systemd services
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - "{{ haproxy_service }}"
    - "{{ keepalived_service }}"

