---
# tasks file for ansible-role-haproxy-remove

- name: Stop and disable haproxy & Keepalived systemd service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  register: command_result
  # Prevent Ansible failing when trying to stop a service that doesn't exist
  failed_when: "command_result is failed and ('find' not in command_result.msg and 'found' not in command_result.msg)"
  with_items:
    - "keepalived"
    - "{{ haproxy_service }}"

- name: Disable non-local IP bindings
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: absent
    reload: yes

- name: Delete haproxy systemd service config
  file:
    path: "/etc/systemd/system/{{ haproxy_service }}.service"
    state: absent

- name: Delete haproxy directory structures
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ haproxy_conf | dirname }}"

- name: Remove haproxy user
  user:
    name: "{{ haproxy_user }}"
    state: absent
    force: yes
    remove: yes

- name: Remove haproxy group
  group:
    name: "{{ haproxy_group }}"
    state: absent

- name: Remove haproxy binary
  file:
    path: "{{ haproxy_bin_path }}/haproxy"
    state: absent

